#!/usr/bin/env node
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { CallToolRequestSchema, ListToolsRequestSchema, ListResourcesRequestSchema, ReadResourceRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { parseGistRef, fetchGist, fetchFileContent, listUserGists, fetchGistCommits, NotFoundError, RateLimitError } from "./gistClient.js";

// Load .env file if dotenv is available
try { const { config } = await import("dotenv"); config(); } catch {}

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(__dirname, "..", "package.json"), "utf8"));
const FetchGistSchema = z.object({ gist: z.string().describe("Gist reference: bare ID (aa5a315d61ae9438b18d), full URL (https://gist.github.com/owner/aa5a315d61ae9438b18d), or owner/id (owner/aa5a315d61ae9438b18d)"), sha: z.string().optional().describe("Optional specific revision SHA to fetch (defaults to latest)") });
const FetchFileContentSchema = z.object({ gist: z.string().describe("Gist ID or reference"), filename: z.string().describe("Filename within the gist to fetch") });
const ListUserGistsSchema = z.object({ username: z.string().describe("GitHub username"), maxPages: z.number().int().min(1).max(10).optional().describe("Maximum pages to fetch (default: 3, max: 10)") });
const SearchGistFilesSchema = z.object({ gist: z.string().describe("Gist ID or reference"), pattern: z.string().describe("Search pattern or filename to match") });
const GetGistHistorySchema = z.object({ gist: z.string().describe("Gist ID or reference") });
class GistMCPServer {
  constructor() { this.server = new Server({ name: pkg.name, version: pkg.version }, { capabilities: { tools: {}, resources: {} } }); this.setupHandlers(); }
  setupHandlers() {
    this.server.setRequestHandler(ListToolsRequestSchema, async () => ({ tools: [{ name: "fetch_gist", description: "Fetch complete gist metadata and file listings. Returns gist info, file manifest, and metadata.", inputSchema: FetchGistSchema.strict() }, { name: "fetch_file_content", description: "Fetch raw content of a specific file within a gist. Handles large files via GitHub raw URLs.", inputSchema: FetchFileContentSchema.strict() }, { name: "list_user_gists", description: "List all public gists for a GitHub user. Paginated results with file counts and update timestamps.", inputSchema: ListUserGistsSchema.strict() }, { name: "search_gist_files", description: "Search for files within a gist by name or pattern. Case-insensitive filename matching.", inputSchema: SearchGistFilesSchema.strict() }, { name: "get_gist_history", description: "Fetch revision history for a gist. Shows all commits with timestamps and file changes.", inputSchema: GetGistHistorySchema.strict() }] }));
    this.server.setRequestHandler(CallToolRequestSchema, async (request) => { try { const { name, arguments: args } = request; switch (name) { case "fetch_gist": return await this.handleFetchGist(args); case "fetch_file_content": return await this.handleFetchFileContent(args); case "list_user_gists": return await this.handleListUserGists(args); case "search_gist_files": return await this.handleSearchGistFiles(args); case "get_gist_history": return await this.handleGetGistHistory(args); default: return { content: [{ type: "text", text: `Unknown tool: ${name}` }], isError: true }; } } catch (error) { return { content: [{ type: "text", text: `Error: ${this.formatError(error)}` }], isError: true }; } });
    this.server.setRequestHandler(ListResourcesRequestSchema, async () => ({ resources: [], resourceTemplates: [{ uriTemplate: "gist://{gistId}", name: "GitHub Gist", description: "A public GitHub Gist", mimeType: "application/json" }, { uriTemplate: "gist://{gistId}/{filename}", name: "Gist File", description: "A file within a GitHub Gist", mimeType: "text/plain" }] }));
    this.server.setRequestHandler(ReadResourceRequestSchema, async (request) => { const uri = request.uri; try { const match = uri.match(/^gist:\/\/([^/]+)(?:\/(.+))?$/); if (!match) return { contents: [{ uri, mimeType: "text/plain", text: "Invalid gist URI format" }] }; const [, gistId, filename] = match; if (filename) { const gist = await fetchGist(gistId); const file = gist.files[filename]; if (!file) return { contents: [{ uri, mimeType: "text/plain", text: `File not found: ${filename}` }] }; const content = await fetchFileContent(file); const mimeType = this.getMimeType(filename); return { contents: [{ uri, mimeType, text: content }] }; } else { const gist = await fetchGist(gistId); return { contents: [{ uri, mimeType: "application/json", text: JSON.stringify(gist, null, 2) }] }; } } catch (error) { return { contents: [{ uri, mimeType: "text/plain", text: `Error: ${this.formatError(error)}` }] }; } });
  }
  async handleFetchGist(args) { const parsed = FetchGistSchema.parse(args); const ref = parseGistRef(parsed.gist); const gist = await fetchGist(ref.gistId, parsed.sha || undefined); const fileList = Object.entries(gist.files).map(([name, meta]) => ({ filename: name, language: meta.language, size: meta.size, truncated: meta.truncated, type: meta.type })); return { content: [{ type: "text", text: JSON.stringify({ id: gist.id, description: gist.description, owner: gist.owner, public: gist.public, html_url: gist.html_url, created_at: gist.created_at, updated_at: gist.updated_at, comments: gist.comments, file_count: fileList.length, files: fileList }, null, 2) }] }; }
  async handleFetchFileContent(args) { const parsed = FetchFileContentSchema.parse(args); const ref = parseGistRef(parsed.gist); const gist = await fetchGist(ref.gistId); const file = gist.files[parsed.filename]; if (!file) throw new NotFoundError(`File "${parsed.filename}" not found in gist ${ref.gistId}`); const content = await fetchFileContent(file); const language = file.language || "text"; return { content: [{ type: "text", text: `# ${parsed.filename} (${language})\n\n${content}` }] }; }
  async handleListUserGists(args) { const parsed = ListUserGistsSchema.parse(args); const gists = await listUserGists(parsed.username, parsed.maxPages || 3); return { content: [{ type: "text", text: JSON.stringify(gists, null, 2) }] }; }
  async handleSearchGistFiles(args) { const parsed = SearchGistFilesSchema.parse(args); const ref = parseGistRef(parsed.gist); const gist = await fetchGist(ref.gistId); let pattern; try { pattern = new RegExp(parsed.pattern, "i"); } catch (e) { throw new Error(`Invalid search pattern "${parsed.pattern}": ${e.message}`); } const matches = Object.entries(gist.files).filter(([name]) => pattern.test(name)).map(([name, meta]) => ({ filename: name, language: meta.language, size: meta.size, type: meta.type })); return { content: [{ type: "text", text: JSON.stringify({ pattern: parsed.pattern, matches: matches.length, files: matches }, null, 2) }] }; }
  async handleGetGistHistory(args) { const parsed = GetGistHistorySchema.parse(args); const ref = parseGistRef(parsed.gist); const commits = await fetchGistCommits(ref.gistId); const history = commits.map((commit) => ({ version: commit.version, user: commit.user?.login || "unknown", committed_at: commit.committed_at, change_status: commit.change_status, url: commit.url })); return { content: [{ type: "text", text: JSON.stringify({ gist_id: ref.gistId, total_commits: history.length, commits: history }, null, 2) }] }; }
  getMimeType(filename) { const ext = filename.split(".").pop()?.toLowerCase() || ""; const mimeMap = { js: "application/javascript", json: "application/json", py: "text/x-python", rb: "text/x-ruby", go: "text/x-go", rs: "text/x-rust", ts: "application/typescript", tsx: "application/typescript", jsx: "application/javascript", java: "text/x-java", c: "text/x-csrc", cpp: "text/x-c++src", h: "text/x-csrc", hpp: "text/x-c++src", cs: "text/x-csharp", sh: "text/x-shellscript", bash: "text/x-shellscript", zsh: "text/x-shellscript", fish: "text/x-shellscript", sql: "text/x-sql", html: "text/html", css: "text/css", xml: "text/xml", yaml: "text/yaml", yml: "text/yaml", toml: "text/toml", md: "text/markdown", txt: "text/plain" }; return mimeMap[ext] || "text/plain"; }
  formatError(error) { if (error instanceof NotFoundError) return `Not found: ${error.message}`; if (error instanceof RateLimitError) return `Rate limited: ${error.message}`; if (error instanceof z.ZodError) return `Invalid arguments: ${error.errors.map((e) => `${e.path.join(".")}: ${e.message}`).join(", ")}`; return error instanceof Error ? error.message : String(error); }
  async run() { const transport = new StdioServerTransport(); await this.server.connect(transport); console.error("[gist-mcp] Server connected on stdio transport"); }
}
const server = new GistMCPServer();
server.run().catch((err) => { console.error("[gist-mcp] Fatal error:", err); process.exit(1); });
